version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - ${mongodb_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${mongodb_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${mongodb_PASSWORD}
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - mongodb_PORT=27017
  app:
    build:
      context: .
      args:
        PORT: ${PORT}
        APP_DIR: ${APP_DIR}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:${APP_DIR}
      - ${APP_DIR}node_modules
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - APP_DIR=/app
      - DATABASE_URL=mongodb://mongo:27017/url-shortener-db
  client:
    build: ./src/client
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    depends_on:
      - app
    environment:
      - VUE_APP_SERVER_URL=http://localhost:5000/urls
      - CLIENT_PORT=8080
